=== MouadErghout/DB/env.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.example.com/DBS"
            targetNamespace="http://www.example.com/DBS"
            elementFormDefault="qualified">

	<xsd:element name="DBS">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SqlServer" type="SqlServerType"/>
				<xsd:element name="Mysql" type="MysqlType"/>
				<xsd:element name="Oracle" type="OracleType"/>
			</xsd:sequence>
			<xsd:attribute name="xsi:schemaLocation" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="SqlServerType">
		<xsd:sequence>
			<xsd:element name="Server" type="xsd:string"/>
			<xsd:element name="InitialCatalog" type="xsd:string"/>
			<xsd:element name="IntegratedSecurity" type="xsd:boolean"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="MysqlType">
		<xsd:sequence>
			<xsd:element name="Server" type="xsd:string"/>
			<xsd:element name="uid" type="xsd:string"/>
			<xsd:element name="pwd" type="xsd:string"/>
			<xsd:element name="Database" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="OracleType">
		<xsd:sequence>
			<xsd:element name="Server" type="xsd:string"/>
			<xsd:element name="TNS_ADMIN" type="xsd:string"/>
			<xsd:element name="USER_ID" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== MouadErghout/DB/env.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="./env.xsl"?>
<DBS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=" env ./env.xsd">
	<SqlServer>
		<Server>localhost</Server>
		<InitialCatalog>ENSA_TANGER</InitialCatalog>
		<IntegratedSecurity>True</IntegratedSecurity>
	</SqlServer>
	<MySql>
		<Server>localhost</Server>
		<uid>root</uid>
		<pwd></pwd>
		<Database>ENSA_TANGER</Database>
	</MySql>
	<Oracle>
		<Server>localhost:1521/orclpdb</Server>
		<TNS_ADMIN>C:\\Users\\mouad\\Oracle\\network\\admin</TNS_ADMIN>
		<USER_ID>ENSA_TANGER</USER_ID>
	</Oracle>
</DBS>
